import { createFileRoute, Link, notFound } from '@tanstack/react-router'
import { createServerFn } from '@tanstack/react-start'
import { listChapters, loadChapter } from '~/lib/docs'
import { DocsSidebar } from '~/components/DocsSidebar'

const getChapterPage = createServerFn({ method: 'GET' })
  .inputValidator((slug: unknown): string => {
    if (typeof slug !== 'string') throw new Error('slug required')
    return slug
  })
  .handler(async ({ data: slug }) => {
    const [chapter, chapters] = await Promise.all([
      loadChapter(slug),
      listChapters(),
    ])
    if (!chapter) return null
    return { chapter, chapters }
  })

export const Route = createFileRoute('/docs/$slug')({
  loader: async ({ params }) => {
    const data = await getChapterPage({ data: params.slug })
    if (!data) throw notFound()
    return data
  },
  head: ({ loaderData }) =>
    loaderData
      ? {
          meta: [
            {
              title: `${loaderData.chapter.title} — PDS docs`,
            },
            ...(loaderData.chapter.blurb
              ? [{ name: 'description', content: loaderData.chapter.blurb }]
              : []),
          ],
        }
      : {},
  component: ChapterPage,
  notFoundComponent: () => (
    <div className="mx-auto max-w-3xl px-6 py-20">
      <h1 className="text-2xl">Chapter not found</h1>
      <Link to="/docs" className="text-[var(--color-accent)] underline">
        ← Back to all chapters
      </Link>
    </div>
  ),
})

function ChapterPage() {
  const { chapter, chapters } = Route.useLoaderData()
  return (
    <div className="mx-auto flex max-w-6xl">
      <DocsSidebar chapters={chapters} activeSlug={chapter.slug} />
      <main className="flex-1 px-6 py-10 md:px-12 min-w-0">
        <p className="font-mono text-xs uppercase tracking-widest text-[var(--color-accent-2)]">
          Chapter {String(chapter.number ?? 0).padStart(2, '0')}
        </p>
        <article
          className="prose prose-invert prose-zinc mt-3 max-w-none prose-headings:tracking-tight prose-headings:font-semibold prose-pre:my-4 prose-code:before:hidden prose-code:after:hidden"
          // The HTML is generated by our trusted markdown pipeline from
          // files we author. allowDangerousHtml is off in the processor, so
          // there's no raw HTML pass-through from chapter content.
          dangerouslySetInnerHTML={{ __html: chapter.html }}
        />
        <nav className="mt-16 grid gap-3 border-t border-[var(--color-border)] pt-8 md:grid-cols-2">
          {chapter.prev ? (
            <Link
              to="/docs/$slug"
              params={{ slug: chapter.prev.slug }}
              className="rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] p-4 hover:border-[var(--color-accent)]/60 transition-colors"
            >
              <p className="text-xs text-[var(--color-fg-muted)]">
                ← Previous
              </p>
              <p className="mt-1 text-sm font-medium">{chapter.prev.title}</p>
            </Link>
          ) : (
            <span />
          )}
          {chapter.next ? (
            <Link
              to="/docs/$slug"
              params={{ slug: chapter.next.slug }}
              className="rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] p-4 text-right hover:border-[var(--color-accent)]/60 transition-colors"
            >
              <p className="text-xs text-[var(--color-fg-muted)]">Next →</p>
              <p className="mt-1 text-sm font-medium">{chapter.next.title}</p>
            </Link>
          ) : (
            <span />
          )}
        </nav>
      </main>
    </div>
  )
}
