/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as XrpcNsidRouteImport } from './routes/xrpc/$nsid'
import { Route as OauthTokenRouteImport } from './routes/oauth/token'
import { Route as OauthRevokeRouteImport } from './routes/oauth/revoke'
import { Route as OauthParRouteImport } from './routes/oauth/par'
import { Route as OauthJwksRouteImport } from './routes/oauth/jwks'
import { Route as OauthAuthorizeRouteImport } from './routes/oauth/authorize'
import { Route as DocsSlugRouteImport } from './routes/docs/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const XrpcNsidRoute = XrpcNsidRouteImport.update({
  id: '/xrpc/$nsid',
  path: '/xrpc/$nsid',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthTokenRoute = OauthTokenRouteImport.update({
  id: '/oauth/token',
  path: '/oauth/token',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthRevokeRoute = OauthRevokeRouteImport.update({
  id: '/oauth/revoke',
  path: '/oauth/revoke',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthParRoute = OauthParRouteImport.update({
  id: '/oauth/par',
  path: '/oauth/par',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthJwksRoute = OauthJwksRouteImport.update({
  id: '/oauth/jwks',
  path: '/oauth/jwks',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthAuthorizeRoute = OauthAuthorizeRouteImport.update({
  id: '/oauth/authorize',
  path: '/oauth/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/oauth/jwks': typeof OauthJwksRoute
  '/oauth/par': typeof OauthParRoute
  '/oauth/revoke': typeof OauthRevokeRoute
  '/oauth/token': typeof OauthTokenRoute
  '/xrpc/$nsid': typeof XrpcNsidRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/oauth/jwks': typeof OauthJwksRoute
  '/oauth/par': typeof OauthParRoute
  '/oauth/revoke': typeof OauthRevokeRoute
  '/oauth/token': typeof OauthTokenRoute
  '/xrpc/$nsid': typeof XrpcNsidRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/oauth/jwks': typeof OauthJwksRoute
  '/oauth/par': typeof OauthParRoute
  '/oauth/revoke': typeof OauthRevokeRoute
  '/oauth/token': typeof OauthTokenRoute
  '/xrpc/$nsid': typeof XrpcNsidRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs/$slug'
    | '/oauth/authorize'
    | '/oauth/jwks'
    | '/oauth/par'
    | '/oauth/revoke'
    | '/oauth/token'
    | '/xrpc/$nsid'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/$slug'
    | '/oauth/authorize'
    | '/oauth/jwks'
    | '/oauth/par'
    | '/oauth/revoke'
    | '/oauth/token'
    | '/xrpc/$nsid'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/docs/$slug'
    | '/oauth/authorize'
    | '/oauth/jwks'
    | '/oauth/par'
    | '/oauth/revoke'
    | '/oauth/token'
    | '/xrpc/$nsid'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsSlugRoute: typeof DocsSlugRoute
  OauthAuthorizeRoute: typeof OauthAuthorizeRoute
  OauthJwksRoute: typeof OauthJwksRoute
  OauthParRoute: typeof OauthParRoute
  OauthRevokeRoute: typeof OauthRevokeRoute
  OauthTokenRoute: typeof OauthTokenRoute
  XrpcNsidRoute: typeof XrpcNsidRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xrpc/$nsid': {
      id: '/xrpc/$nsid'
      path: '/xrpc/$nsid'
      fullPath: '/xrpc/$nsid'
      preLoaderRoute: typeof XrpcNsidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/token': {
      id: '/oauth/token'
      path: '/oauth/token'
      fullPath: '/oauth/token'
      preLoaderRoute: typeof OauthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/revoke': {
      id: '/oauth/revoke'
      path: '/oauth/revoke'
      fullPath: '/oauth/revoke'
      preLoaderRoute: typeof OauthRevokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/par': {
      id: '/oauth/par'
      path: '/oauth/par'
      fullPath: '/oauth/par'
      preLoaderRoute: typeof OauthParRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/jwks': {
      id: '/oauth/jwks'
      path: '/oauth/jwks'
      fullPath: '/oauth/jwks'
      preLoaderRoute: typeof OauthJwksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/authorize': {
      id: '/oauth/authorize'
      path: '/oauth/authorize'
      fullPath: '/oauth/authorize'
      preLoaderRoute: typeof OauthAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsSlugRoute: DocsSlugRoute,
  OauthAuthorizeRoute: OauthAuthorizeRoute,
  OauthJwksRoute: OauthJwksRoute,
  OauthParRoute: OauthParRoute,
  OauthRevokeRoute: OauthRevokeRoute,
  OauthTokenRoute: OauthTokenRoute,
  XrpcNsidRoute: XrpcNsidRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
