/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModIndexRouteImport } from './routes/mod/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as XrpcNsidRouteImport } from './routes/xrpc/$nsid'
import { Route as OauthTokenRouteImport } from './routes/oauth/token'
import { Route as OauthRevokeRouteImport } from './routes/oauth/revoke'
import { Route as OauthParRouteImport } from './routes/oauth/par'
import { Route as OauthJwksRouteImport } from './routes/oauth/jwks'
import { Route as OauthAuthorizeRouteImport } from './routes/oauth/authorize'
import { Route as ModTeamRouteImport } from './routes/mod/team'
import { Route as ModSubjectRouteImport } from './routes/mod/subject'
import { Route as ModLogoutRouteImport } from './routes/mod/logout'
import { Route as ModLoginRouteImport } from './routes/mod/login'
import { Route as ModLabelsRouteImport } from './routes/mod/labels'
import { Route as ModEventsRouteImport } from './routes/mod/events'
import { Route as InternalTlsCheckRouteImport } from './routes/internal/tls-check'
import { Route as DocsSlugRouteImport } from './routes/docs/$slug'
import { Route as AppFeedRouteImport } from './routes/app/feed'
import { Route as AppComposeRouteImport } from './routes/app/compose'
import { Route as AdminSignupsRouteImport } from './routes/admin/signups'
import { Route as AdminLogoutRouteImport } from './routes/admin/logout'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminInvitesRouteImport } from './routes/admin/invites'
import { Route as Char91DotwellKnownChar93FileRouteImport } from './routes/[.well-known]/$file'

const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModIndexRoute = ModIndexRouteImport.update({
  id: '/mod/',
  path: '/mod/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const XrpcNsidRoute = XrpcNsidRouteImport.update({
  id: '/xrpc/$nsid',
  path: '/xrpc/$nsid',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthTokenRoute = OauthTokenRouteImport.update({
  id: '/oauth/token',
  path: '/oauth/token',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthRevokeRoute = OauthRevokeRouteImport.update({
  id: '/oauth/revoke',
  path: '/oauth/revoke',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthParRoute = OauthParRouteImport.update({
  id: '/oauth/par',
  path: '/oauth/par',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthJwksRoute = OauthJwksRouteImport.update({
  id: '/oauth/jwks',
  path: '/oauth/jwks',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthAuthorizeRoute = OauthAuthorizeRouteImport.update({
  id: '/oauth/authorize',
  path: '/oauth/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ModTeamRoute = ModTeamRouteImport.update({
  id: '/mod/team',
  path: '/mod/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ModSubjectRoute = ModSubjectRouteImport.update({
  id: '/mod/subject',
  path: '/mod/subject',
  getParentRoute: () => rootRouteImport,
} as any)
const ModLogoutRoute = ModLogoutRouteImport.update({
  id: '/mod/logout',
  path: '/mod/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ModLoginRoute = ModLoginRouteImport.update({
  id: '/mod/login',
  path: '/mod/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ModLabelsRoute = ModLabelsRouteImport.update({
  id: '/mod/labels',
  path: '/mod/labels',
  getParentRoute: () => rootRouteImport,
} as any)
const ModEventsRoute = ModEventsRouteImport.update({
  id: '/mod/events',
  path: '/mod/events',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalTlsCheckRoute = InternalTlsCheckRouteImport.update({
  id: '/internal/tls-check',
  path: '/internal/tls-check',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppComposeRoute = AppComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminSignupsRoute = AdminSignupsRouteImport.update({
  id: '/admin/signups',
  path: '/admin/signups',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogoutRoute = AdminLogoutRouteImport.update({
  id: '/admin/logout',
  path: '/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvitesRoute = AdminInvitesRouteImport.update({
  id: '/admin/invites',
  path: '/admin/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93FileRoute =
  Char91DotwellKnownChar93FileRouteImport.update({
    id: '/.well-known/$file',
    path: '/.well-known/$file',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/metrics': typeof MetricsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/.well-known/$file': typeof Char91DotwellKnownChar93FileRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logout': typeof AdminLogoutRoute
  '/admin/signups': typeof AdminSignupsRoute
  '/app/compose': typeof AppComposeRoute
  '/app/feed': typeof AppFeedRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/internal/tls-check': typeof InternalTlsCheckRoute
  '/mod/events': typeof ModEventsRoute
  '/mod/labels': typeof ModLabelsRoute
  '/mod/login': typeof ModLoginRoute
  '/mod/logout': typeof ModLogoutRoute
  '/mod/subject': typeof ModSubjectRoute
  '/mod/team': typeof ModTeamRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/oauth/jwks': typeof OauthJwksRoute
  '/oauth/par': typeof OauthParRoute
  '/oauth/revoke': typeof OauthRevokeRoute
  '/oauth/token': typeof OauthTokenRoute
  '/xrpc/$nsid': typeof XrpcNsidRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/mod/': typeof ModIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/metrics': typeof MetricsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/.well-known/$file': typeof Char91DotwellKnownChar93FileRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logout': typeof AdminLogoutRoute
  '/admin/signups': typeof AdminSignupsRoute
  '/app/compose': typeof AppComposeRoute
  '/app/feed': typeof AppFeedRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/internal/tls-check': typeof InternalTlsCheckRoute
  '/mod/events': typeof ModEventsRoute
  '/mod/labels': typeof ModLabelsRoute
  '/mod/login': typeof ModLoginRoute
  '/mod/logout': typeof ModLogoutRoute
  '/mod/subject': typeof ModSubjectRoute
  '/mod/team': typeof ModTeamRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/oauth/jwks': typeof OauthJwksRoute
  '/oauth/par': typeof OauthParRoute
  '/oauth/revoke': typeof OauthRevokeRoute
  '/oauth/token': typeof OauthTokenRoute
  '/xrpc/$nsid': typeof XrpcNsidRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/docs': typeof DocsIndexRoute
  '/mod': typeof ModIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/metrics': typeof MetricsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/.well-known/$file': typeof Char91DotwellKnownChar93FileRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logout': typeof AdminLogoutRoute
  '/admin/signups': typeof AdminSignupsRoute
  '/app/compose': typeof AppComposeRoute
  '/app/feed': typeof AppFeedRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/internal/tls-check': typeof InternalTlsCheckRoute
  '/mod/events': typeof ModEventsRoute
  '/mod/labels': typeof ModLabelsRoute
  '/mod/login': typeof ModLoginRoute
  '/mod/logout': typeof ModLogoutRoute
  '/mod/subject': typeof ModSubjectRoute
  '/mod/team': typeof ModTeamRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/oauth/jwks': typeof OauthJwksRoute
  '/oauth/par': typeof OauthParRoute
  '/oauth/revoke': typeof OauthRevokeRoute
  '/oauth/token': typeof OauthTokenRoute
  '/xrpc/$nsid': typeof XrpcNsidRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/mod/': typeof ModIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/metrics'
    | '/robots.txt'
    | '/.well-known/$file'
    | '/admin/invites'
    | '/admin/login'
    | '/admin/logout'
    | '/admin/signups'
    | '/app/compose'
    | '/app/feed'
    | '/docs/$slug'
    | '/internal/tls-check'
    | '/mod/events'
    | '/mod/labels'
    | '/mod/login'
    | '/mod/logout'
    | '/mod/subject'
    | '/mod/team'
    | '/oauth/authorize'
    | '/oauth/jwks'
    | '/oauth/par'
    | '/oauth/revoke'
    | '/oauth/token'
    | '/xrpc/$nsid'
    | '/admin/'
    | '/app/'
    | '/docs/'
    | '/mod/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/metrics'
    | '/robots.txt'
    | '/.well-known/$file'
    | '/admin/invites'
    | '/admin/login'
    | '/admin/logout'
    | '/admin/signups'
    | '/app/compose'
    | '/app/feed'
    | '/docs/$slug'
    | '/internal/tls-check'
    | '/mod/events'
    | '/mod/labels'
    | '/mod/login'
    | '/mod/logout'
    | '/mod/subject'
    | '/mod/team'
    | '/oauth/authorize'
    | '/oauth/jwks'
    | '/oauth/par'
    | '/oauth/revoke'
    | '/oauth/token'
    | '/xrpc/$nsid'
    | '/admin'
    | '/app'
    | '/docs'
    | '/mod'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/metrics'
    | '/robots.txt'
    | '/.well-known/$file'
    | '/admin/invites'
    | '/admin/login'
    | '/admin/logout'
    | '/admin/signups'
    | '/app/compose'
    | '/app/feed'
    | '/docs/$slug'
    | '/internal/tls-check'
    | '/mod/events'
    | '/mod/labels'
    | '/mod/login'
    | '/mod/logout'
    | '/mod/subject'
    | '/mod/team'
    | '/oauth/authorize'
    | '/oauth/jwks'
    | '/oauth/par'
    | '/oauth/revoke'
    | '/oauth/token'
    | '/xrpc/$nsid'
    | '/admin/'
    | '/app/'
    | '/docs/'
    | '/mod/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  MetricsRoute: typeof MetricsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  Char91DotwellKnownChar93FileRoute: typeof Char91DotwellKnownChar93FileRoute
  AdminInvitesRoute: typeof AdminInvitesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminLogoutRoute: typeof AdminLogoutRoute
  AdminSignupsRoute: typeof AdminSignupsRoute
  DocsSlugRoute: typeof DocsSlugRoute
  InternalTlsCheckRoute: typeof InternalTlsCheckRoute
  ModEventsRoute: typeof ModEventsRoute
  ModLabelsRoute: typeof ModLabelsRoute
  ModLoginRoute: typeof ModLoginRoute
  ModLogoutRoute: typeof ModLogoutRoute
  ModSubjectRoute: typeof ModSubjectRoute
  ModTeamRoute: typeof ModTeamRoute
  OauthAuthorizeRoute: typeof OauthAuthorizeRoute
  OauthJwksRoute: typeof OauthJwksRoute
  OauthParRoute: typeof OauthParRoute
  OauthRevokeRoute: typeof OauthRevokeRoute
  OauthTokenRoute: typeof OauthTokenRoute
  XrpcNsidRoute: typeof XrpcNsidRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  ModIndexRoute: typeof ModIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mod/': {
      id: '/mod/'
      path: '/mod'
      fullPath: '/mod/'
      preLoaderRoute: typeof ModIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xrpc/$nsid': {
      id: '/xrpc/$nsid'
      path: '/xrpc/$nsid'
      fullPath: '/xrpc/$nsid'
      preLoaderRoute: typeof XrpcNsidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/token': {
      id: '/oauth/token'
      path: '/oauth/token'
      fullPath: '/oauth/token'
      preLoaderRoute: typeof OauthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/revoke': {
      id: '/oauth/revoke'
      path: '/oauth/revoke'
      fullPath: '/oauth/revoke'
      preLoaderRoute: typeof OauthRevokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/par': {
      id: '/oauth/par'
      path: '/oauth/par'
      fullPath: '/oauth/par'
      preLoaderRoute: typeof OauthParRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/jwks': {
      id: '/oauth/jwks'
      path: '/oauth/jwks'
      fullPath: '/oauth/jwks'
      preLoaderRoute: typeof OauthJwksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/authorize': {
      id: '/oauth/authorize'
      path: '/oauth/authorize'
      fullPath: '/oauth/authorize'
      preLoaderRoute: typeof OauthAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mod/team': {
      id: '/mod/team'
      path: '/mod/team'
      fullPath: '/mod/team'
      preLoaderRoute: typeof ModTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mod/subject': {
      id: '/mod/subject'
      path: '/mod/subject'
      fullPath: '/mod/subject'
      preLoaderRoute: typeof ModSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mod/logout': {
      id: '/mod/logout'
      path: '/mod/logout'
      fullPath: '/mod/logout'
      preLoaderRoute: typeof ModLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mod/login': {
      id: '/mod/login'
      path: '/mod/login'
      fullPath: '/mod/login'
      preLoaderRoute: typeof ModLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mod/labels': {
      id: '/mod/labels'
      path: '/mod/labels'
      fullPath: '/mod/labels'
      preLoaderRoute: typeof ModLabelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mod/events': {
      id: '/mod/events'
      path: '/mod/events'
      fullPath: '/mod/events'
      preLoaderRoute: typeof ModEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/tls-check': {
      id: '/internal/tls-check'
      path: '/internal/tls-check'
      fullPath: '/internal/tls-check'
      preLoaderRoute: typeof InternalTlsCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/feed': {
      id: '/app/feed'
      path: '/feed'
      fullPath: '/app/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/compose': {
      id: '/app/compose'
      path: '/compose'
      fullPath: '/app/compose'
      preLoaderRoute: typeof AppComposeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/signups': {
      id: '/admin/signups'
      path: '/admin/signups'
      fullPath: '/admin/signups'
      preLoaderRoute: typeof AdminSignupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logout': {
      id: '/admin/logout'
      path: '/admin/logout'
      fullPath: '/admin/logout'
      preLoaderRoute: typeof AdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/invites': {
      id: '/admin/invites'
      path: '/admin/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof AdminInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/$file': {
      id: '/.well-known/$file'
      path: '/.well-known/$file'
      fullPath: '/.well-known/$file'
      preLoaderRoute: typeof Char91DotwellKnownChar93FileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppComposeRoute: typeof AppComposeRoute
  AppFeedRoute: typeof AppFeedRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppComposeRoute: AppComposeRoute,
  AppFeedRoute: AppFeedRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  MetricsRoute: MetricsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  Char91DotwellKnownChar93FileRoute: Char91DotwellKnownChar93FileRoute,
  AdminInvitesRoute: AdminInvitesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminLogoutRoute: AdminLogoutRoute,
  AdminSignupsRoute: AdminSignupsRoute,
  DocsSlugRoute: DocsSlugRoute,
  InternalTlsCheckRoute: InternalTlsCheckRoute,
  ModEventsRoute: ModEventsRoute,
  ModLabelsRoute: ModLabelsRoute,
  ModLoginRoute: ModLoginRoute,
  ModLogoutRoute: ModLogoutRoute,
  ModSubjectRoute: ModSubjectRoute,
  ModTeamRoute: ModTeamRoute,
  OauthAuthorizeRoute: OauthAuthorizeRoute,
  OauthJwksRoute: OauthJwksRoute,
  OauthParRoute: OauthParRoute,
  OauthRevokeRoute: OauthRevokeRoute,
  OauthTokenRoute: OauthTokenRoute,
  XrpcNsidRoute: XrpcNsidRoute,
  AdminIndexRoute: AdminIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  ModIndexRoute: ModIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
